// Laboratory work 6: conservation of mechanical energy on an inclined plane.
//
// The cart is released near the top of a ramp and the three energies are drawn
// as bars standing on the bench next to it. Watching the purple bar drain into
// the green one — and, when μ > 0, into the red one that never comes back — is
// the whole lesson, and it is far more legible at eye level than on a chart.

import {
  BENCH_H,
  buildArrow,
  buildBench,
  buildRamp,
  MAT,
  type ArrowModel,
} from "../three-models";
import { loadPascoDevice } from "../pasco-loader";
import type { LabRig, RigContext, RigParams } from "../types";
import type * as THREE_NS from "three";

const G = 9.81;
const RAMP_L = 1.0;
/** Where the cart is released, measured along the ramp from the hinge. */
const D_START = 0.86;
/** The end stop at the foot of the ramp. */
const D_MIN = 0.13;

interface State {
  /** Distance from the hinge along the ramp surface. */
  d: number;
  /** Speed down the slope (m/s, positive = descending). */
  u: number;
  /** Heat generated by friction so far. */
  Q: number;
  stopped: boolean;
}

const BAR_COLORS = ["#a855f7", "#10b981", "#f43f5e"];
/** Height (m) of a bar holding all of the energy the cart started with. */
const BAR_FULL = 0.34;

export function createEnergyRig({ THREE, params }: RigContext): LabRig {
  const object = new THREE.Group();
  object.name = "rig-energy";
  const content = new THREE.Group();
  content.position.x = -RAMP_L / 2;
  object.add(content);

  content.add(buildBench(THREE, { width: 1.7, depth: 0.7 }).translateX(RAMP_L / 2));

  const ramp = buildRamp(THREE, { length: RAMP_L, width: 0.15 });
  ramp.position.set(0, BENCH_H, 0);
  content.add(ramp);
  const surface = ramp.userData.surface as THREE_NS.Group;

  // Jack holding the high end up. A unit-height box that is simply scaled, so
  // changing the angle costs nothing.
  const jack = new THREE.Mesh(
    new THREE.BoxGeometry(0.07, 1, 0.13),
    new THREE.MeshStandardMaterial({ color: "#64748b", roughness: 0.6, metalness: 0.2 })
  );
  jack.castShadow = true;
  content.add(jack);

  // The cart rides inside the ramp's rotating group, so it tilts with the slope.
  const cart = new THREE.Group();
  cart.position.set(D_START, 0.014, 0);
  cart.add(loadPascoDevice(THREE, "smartCart").object);
  surface.add(cart);

  const sensor = new THREE.Group();
  sensor.position.set(-0.1, BENCH_H, 0);
  sensor.rotation.y = Math.PI / 2;
  sensor.add(loadPascoDevice(THREE, "motionSensor").object);
  content.add(sensor);

  const vArrow: ArrowModel = buildArrow(THREE, { color: "#10b981", radius: 0.005 });
  surface.add(vArrow.object);

  // Energy bars: potential, kinetic, heat.
  const bars: THREE_NS.Mesh[] = [];
  const barBase = new THREE.Group();
  // Toward the front-right corner of the bench, clear of the instrument panels
  // hanging behind the apparatus.
  barBase.position.set(RAMP_L + 0.16, BENCH_H, 0.19);
  content.add(barBase);
  for (let i = 0; i < 3; i += 1) {
    const bar = new THREE.Mesh(
      new THREE.BoxGeometry(0.058, 1, 0.058),
      new THREE.MeshStandardMaterial({
        color: BAR_COLORS[i],
        roughness: 0.4,
        metalness: 0.05,
        emissive: new THREE.Color(BAR_COLORS[i]),
        emissiveIntensity: 0.22,
      })
    );
    bar.castShadow = true;
    bar.position.set(0, 0, (i - 1) * 0.085);
    barBase.add(bar);
    bars.push(bar);
    // Ghost column at full scale behind each bar. Without it a bar that has
    // drained to a tenth of its height reads as "small", not as "a tenth".
    const ghost = new THREE.Mesh(
      new THREE.BoxGeometry(0.062, BAR_FULL, 0.062),
      new THREE.MeshBasicMaterial({
        color: BAR_COLORS[i],
        transparent: true,
        opacity: 0.1,
      })
    );
    ghost.position.set(0, BAR_FULL / 2 + 0.008, (i - 1) * 0.085);
    barBase.add(ghost);
    // Plinth under each bar, so a zero-height bar still marks its column.
    const plinth = new THREE.Mesh(
      new THREE.BoxGeometry(0.065, 0.008, 0.065),
      new THREE.MeshStandardMaterial({ color: MAT.benchEdge, roughness: 0.7 })
    );
    plinth.position.set(0, 0.004, (i - 1) * 0.085);
    barBase.add(plinth);
  }

  const state: State = { d: D_START, u: 0, Q: 0, stopped: false };
  let current: RigParams = { ...params };

  const p0 = new THREE.Vector3();
  const dir = new THREE.Vector3();

  function energies(p: RigParams) {
    const rad = (p.angle * Math.PI) / 180;
    const h = state.d * Math.sin(rad);
    const Ep = p.mass * G * h;
    const Ek = 0.5 * p.mass * state.u * state.u;
    return { rad, h, Ep, Ek, Q: state.Q, total: Ep + Ek + state.Q };
  }

  function sync(p: RigParams) {
    const rad = (p.angle * Math.PI) / 180;
    surface.rotation.z = rad;
    const rise = RAMP_L * Math.sin(rad);
    jack.scale.y = Math.max(rise, 0.001);
    jack.position.set(RAMP_L * Math.cos(rad), BENCH_H + rise / 2, 0);

    cart.position.x = state.d;

    p0.set(state.d - 0.05, 0.075, 0);
    dir.set(-1, 0, 0);
    vArrow.set(p0, dir, Math.min(Math.abs(state.u) * 0.16, 0.3));

    const e = energies(p);
    // Bars are scaled against the energy the cart started with, so a full bar
    // always means "all of it" no matter which mass or angle is set.
    const ref = Math.max(p.mass * G * D_START * Math.sin(rad), 1e-4);
    const heights = [e.Ep, e.Ek, e.Q].map((v) => Math.max((v / ref) * BAR_FULL, 0.002));
    heights.forEach((hgt, i) => {
      bars[i].scale.y = hgt;
      bars[i].position.y = hgt / 2 + 0.008;
    });
  }

  sync(params);

  return {
    object,

    reset(p: RigParams) {
      current = p;
      state.d = D_START;
      state.u = 0;
      state.Q = 0;
      state.stopped = false;
      sync(p);
    },

    step(h: number, p: RigParams) {
      current = p;
      if (!state.stopped) {
        const rad = (p.angle * Math.PI) / 180;
        const driving = G * Math.sin(rad);
        const resisting = p.mu * G * Math.cos(rad);

        if (state.u <= 1e-6 && driving <= resisting) {
          // Steep enough friction: the cart never starts. tan α ≤ μ.
          state.u = 0;
        } else {
          state.u += (driving - resisting) * h;
          if (state.u < 0) state.u = 0;
          const ds = state.u * h;
          state.d -= ds;
          state.Q += p.mu * p.mass * G * Math.cos(rad) * ds;
        }

        if (state.d <= D_MIN) {
          state.d = D_MIN;
          state.u = 0;
          state.stopped = true;
        }
      }
      sync(p);
    },

    read() {
      const e = energies(current);
      return { h: e.h, v: state.u, Ep: e.Ep, Ek: e.Ek, Q: e.Q, Etotal: e.total };
    },

    finished: () => state.stopped,

    dispose() {},
  };
}
